#!/usr/bin/python3

'''
Freakin' Awesome Dynamic DNS client - GUI version.

Usage:
  faddnsc [options] [-u, --url-prefix=<url-prefix>]...

Options:
  -h, --help      Help.
  --log-level DEBUG | INFO | WARNING | ERROR
                  Debug level [default: INFO].
  -c <config_fn>  Config file path.
  --host=<host>   Hostname to report.
  -i, --interval=<interval>
                  Update interval (s).
  -u, --url-prefix=<url-prefix>
                  URL prefix.
'''

from version import __version__

import os
import sys
from PySide.QtCore import *
from PySide.QtGui import *
import time
from cfg import cfg
import docopt

import logging
sys.excepthook = lambda t, v, tb: logging.critical('unhandled exception', exc_info=(t, v, tb))

from faddns import *


get_addrs = None  # TODO: ugly


class MyTray(QSystemTrayIcon):
	def __init__(self, app, url_prefix):
		icon = QIcon('faddns.png')
		super().__init__(icon)

		self.app = app
		self.url_prefix = url_prefix

		self.addrs_old = None

		self.setToolTip('faddnsc_gui v%s' % __version__)

		menu = QMenu()
		menu.addAction('Force refresh', self.on_refresh)
		menu.addAction('Exit', self.on_exit)
		self.setContextMenu(menu)

		self.t_last = None
		self.startTimer(100)

		self.show()
	#enddef

	def timerEvent(self, e):
		t = time.monotonic()

		if self.t_last and t - self.t_last < cfg.interval:
			return
		#endif

		addrs = get_addrs()
		logging.debug(str(addrs))

		if addrs != self.addrs_old:
			logging.info('sending info to %s (%s)' % (self.url_prefix, addrs))
			if send_addrs(self.url_prefix, cfg.host, __version__, addrs):
				self.addrs_old = addrs
			else:
				logging.warning('send_addrs failed')
			#endif
		else:
			logging.debug('no change, doing nothing')
		#endif

		self.t_last = t
	#enddef

	def on_refresh(self):
		logging.info('forced refresh')

		addrs = get_addrs()
		logging.debug(str(addrs))

		for url_prefix in self.url_prefix:
			logging.info('sending info to %s' % url_prefix)
		#endfor
	#enddef

	def on_exit(self):
		self.app.quit()
	#enddef
#endclass


def main():
	args = docopt.docopt(__doc__, version=__version__)

	log_level = args['--log-level']
	logging_setup(log_level, 'faddnsc_gui.log')

	logging.info('*' * 40)
	logging.info('starting faddnsc_gui v%s' % __version__)

	logging.debug(str(args))

	cfg_fn = args['-c']
	if not cfg_fn:
		for fn in (os.path.expanduser('~/.faddnsc.conf'), 'faddnsc.ini', '/etc/faddnsc.conf'):
			if not os.path.isfile(fn): continue
			cfg_fn = fn
			break
		#endfor
	#endif

	if cfg_fn and not os.path.isfile(cfg_fn):
		logging.critical('%s does not exist, exitting')
		return
	#endif

	if cfg_fn:
		logging.info('reading configuration from %s' % cfg_fn)
		cfg.read_from_ini(cfg_fn)
	else:
		logging.info('no configuration file specified nor found')
	#endif

	if args['--host']: cfg.host = args['--host']
	if args['--interval']: cfg.interval = float(args['--interval'])
	if args['--url-prefix']: cfg.url_prefix = args['--url-prefix']

	err = cfg.check()
	if err:
		logging.critical(err)
		return
	#endif

	logging.info('%s' % cfg)

	global get_addrs
	if sys.platform == 'win32':
		logging.info('detected win32')
		get_addrs = get_addrs_windows
	elif sys.platform.startswith('linux'):
		logging.info('detected linux')
		get_addrs = get_addrs_linux
	else:
		logging.critical('unknown platform! (%s)' % sys.platform)
		return
	#endif

	app = QApplication(sys.argv[1:])

	tray = MyTray(app, cfg.url_prefix)

	app.exec_()

	logging.info('exit')
#enddef


if __name__ == '__main__':
	main()
#endif
